apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeserve1
  template:
    metadata:
      name: kubeserve1
      labels:
        app: kubeserve1
    spec:
      nodeName: aks-agentpool-25452363-vmss000000
      containers:
      - image: leaddevops/kubeserve:v1
        name: app
