kind: CertificateSigningRequest
apiVersion: certificates.k8s.io/v1
metadata:
   name: user1
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FqQ0NBVklDQVFBd0pURVNNQkFHQTFVRUF3d0pjSEp2WkMxMWMyVnlNUTh3RFFZRFZRUUtEQVprWlhadgpjSE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzBCRmsvMzlDU2RhSjhiVTYrCnMvbjRJQzBmV0xlSU01QnFraDN4Yi93T2tMbG1VRk52SFp5V3pUZ0JyQVRvaWJjbVlqWFhzN2JKYWVsY2xZdmsKb2hVRU14emZJMk5nQ0VBMWgvMjBjV2hVazZXYVR1ZGpYUEJ1dDZJZVhiSUNZekkxa0hpbkhHSDZ5WXFZUUREVgpYUitIdU0vVUh2MndxNEh6cjdTaC82VVl5b1A3d29XbkV5WHVhTDFuVjBRY2phZG9zWlNCd3k2SDRBZGZDRFFnClBwN3F4RFcxVTNJQnZQd0Y0bUJ1VHNZZGtMbUJ5aCs3R3o0Z1JyMGpwU2VhWmkzNXZqVHhYT0lIYk5kdTNWME8KVFI0V2dPZDBrRitWZVpQL0d3dFNBelVIQ25YWnl5K2JhbTdhWVM0b1JhZWpJMFhNa2RxUVBTTnZHbVhPTHJTMwozSXc5QWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbW1pQXdMcnJsdlVzMG9tMTU5UW92NFJzCjVTdEdGRVU5Z1E1RkMrclhtM3Fhbmc4d3dqTXl1VmVNcDdrc3lLdUlKWFgvait0N2VsbURpSTNBVG92TnNvTmMKM0EvVDhnNlJCUGMxRk8xVVVxUTVVUS9jUzhvam1URy8zRUVLelBSbHZsNUlhcXA2L1ZmcVQ4a0JwNFBZREtxSgpkWlEzaHdoeW0zQVVGendtaFhMR2RtOVpGQmlVZExNQkJnNFVHZk5VakpwWHRvdVk2VTF2SjN5dWpCVzVWQzU3CjJwR1lvMytKSVhPNDU0RFNOUC96SitvcGxvV3krbW1rdlpDb2hIZ3dQYkhoWld6eVRBTzJmN2d1NjhUL3NRSzgKSXdQOWp2VVMyNk5JaXJQN2NBcm85ZGZnYm1tb0taemJxc21zYlI0bGp1T3B6UHMybDlNV2w5bGZJK2xObGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  #expirationSeconds: 86400
  usages:
  - client auth


# openssl genrsa -out user1.key 2048
# openssl req -config csr.conf -new -key user1.key -nodes -out user1.csr
# cat user1.csr | base64 | tr -d '\n'
# kubectl apply -f csr.yml
# kubectl get csr ; kubectl certificate approve prod-user
# kubectl get csr prod-user -o jsonpath="{.status.certificate}" | base64 --decode > user1.crt
# modify kubeconfig with 
